"""Add handle and profile_image

Revision ID: 3cb4c57d6849
Revises: 87add195396a
Create Date: 2021-12-24 01:12:23.402709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cb4c57d6849'
down_revision = '87add195396a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('handle', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('profile_image', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image')
    op.drop_column('users', 'handle')
    # ### end Alembic commands ###
