"""Modify User table again

Revision ID: 676f08c0a030
Revises: ba0541a683b9
Create Date: 2021-12-12 13:37:14.906896

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '676f08c0a030'
down_revision = 'ba0541a683b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=300),
               type_=sa.LargeBinary(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.LargeBinary(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=300),
               existing_nullable=True)
    # ### end Alembic commands ###
