"""Modify password and salt column

Revision ID: 87add195396a
Revises: 676f08c0a030
Create Date: 2021-12-12 23:52:14.665583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87add195396a'
down_revision = '676f08c0a030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.BLOB(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('users', 'salt',
               existing_type=sa.BLOB(),
               type_=sa.String(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'salt',
               existing_type=sa.String(length=64),
               type_=sa.BLOB(),
               existing_nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.String(length=64),
               type_=sa.BLOB(),
               existing_nullable=True)
    # ### end Alembic commands ###
