"""Modify users_histories table

Revision ID: 8ea79cd6364e
Revises: 935e4862863f
Create Date: 2021-12-12 01:02:01.312099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ea79cd6364e'
down_revision = '935e4862863f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
