"""Create users_histories table

Revision ID: 935e4862863f
Revises: e216ca3ecab6
Create Date: 2021-12-12 01:00:08.299366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '935e4862863f'
down_revision = 'e216ca3ecab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_song_id', sa.String(length=22), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_histories_id'), 'users_histories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_histories_id'), table_name='users_histories')
    op.drop_table('users_histories')
    # ### end Alembic commands ###
